gcc99=c99 -Wall -pedantic

default:
	$(gcc99) ./FizzBuzz_NoArgs.c -o ./FizzBuzz_NoArgs
	$(gcc99) ./FizzBuzz_Args.c -o ./FizzBuzz_Args

No_Args:
	$(gcc99) ./FizzBuzz_NoArgs.c -o ./FizzBuzz_NoArgs

Args:
	$(gcc99) ./FizzBuzz_Args.c -o ./FizzBuzz_Args